language: go

go:
- "1.13"

sudo: false

script:
- make test
- make build

before_deploy:
- mkdir -p bin_release
- GOOS=linux   GOARCH=amd64 go build -o bin_release/flux-checkver_linux-amd64   -ldflags="-X main.AppVersion=$TRAVIS_TAG"
- GOOS=darwin  GOARCH=amd64 go build -o bin_release/flux-checkver_darwin-amd64  -ldflags="-X main.AppVersion=$TRAVIS_TAG"
- GOOS=windows GOARCH=386   go build -o bin_release/flux-checkver_win-i386.exe  -ldflags="-X main.AppVersion=$TRAVIS_TAG"
- GOOS=windows GOARCH=amd64 go build -o bin_release/flux-checkver_win-amd64.exe -ldflags="-X main.AppVersion=$TRAVIS_TAG"

deploy:
  provider: releases
  api_key:
    secure: TDM/GB4X1lbSpYEb3goEv2Mtv1/7a+HhXYP3XQkm3x/rlyYWCCdh9F9I5o91zE8nrWmNowsHm1VdCYiBOgKgmrdZruyyvElC6I/VuN6yLOKQg1fId1P3M7XYP1qYJBxxd6K18DY0dbCMusydXSaftHklR6LmlG01SSPyi4Fu9yf5hEifJS0kBzz5G0AH2IKvvkUcsQnusruYWcxL/JLusUJuwGaabud1+5ceutksoEDLpEPlTS9rDAijWzRy7aGTqU6DufJkkgVs+BmwzacPxu062w3r+s7PlESJBxQNPfUfX4AeE9Etiu/k19mzvGwd6SQA4YAVekNVkPJC4QYSXgpSvoQZ9owrcRuvfmvS9cZxLppBf6/i2utabK8jp+WUQGkQ+mMA7RWBa8AsvkMuKYvFyk64WYHfCYt/0S96Crpr6mI1JKVdNTL4WM8eTbuWAuMuCM3k18t7QAqUvP1BnudhJl07910eYL4U3ws3FPOV7+fHS0nJALBvjAwqdcDWCH/dLJhOCrVHU+kQ3Ra6kZcLYb6f2FW10m33+PBDj2dI4p0BPgGGHFecPbB8lTyPCAfUlLijgh6eyND1yvX0k7N6LxEBBG8wtwJ9HWbVvtuCbKvodZXMN0Jmm53Z2jv+yjvJFWM4Hk2+gD9mFvXyoSMVLzCdnF3/rFM562PKexo=
  file_glob: true
  file: bin_release/*
  skip_cleanup: true
  on:
    tags: true
    go: "1.13"
