FROM bitnami/minideb:stretch

RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y ca-certificates && \
    update-ca-certificates && \
    apt-get clean

USER www-data
COPY bin/release/flux-checkver /flux-checkver
ENTRYPOINT ["/flux-checkver"]
